--- 
files: 
  - 
    destination: /home/ec2-user/webapp/codeDeployApp
    source: /
hooks: 
  AfterInstall: 
    - 
      location: applicationStart.sh
      timeout: 180
os: linux
permissions: 
  - 
    object: /home/ec2-user/webapp/codeDeployApp
version: 0.0
