--- 
files: 
  - 
    destination: /home/ec2-user/webapp/codeDeployApp
    source: /
hooks: 
  AfterInstall: 
    - 
      location: applicationStart.sh
      timeout: 180
os: linux
permissions: 
  - 
    object: /home/ec2-user/webapp/codeDeployApp
    except: [applicationStart.sh]
  - 
    group: ec2-user
    mode: 777
    object: /home/ec2-user/webapp/codeDeployApp/applicationStart.sh
    owner: ec2-user
version: 0.0
